* Where's the Boss Discord Helper Bot
Checkout the rulebook here: https://igaryhe.itch.io/wheres-the-boss
** Setup
   - set the environment variable ~BOT_TOKEN~ to your bot token.
   - ~deno run --allow-env --allow-net main.ts~
** Usage
*** Commands used in a text channel
   - ~!start~ to start the game.
   - ~!stop~ to stop the game.
   - ~!restart~ to restart the game.
   - ~!assign <@player1> ...~ to assign roles to players. This command accept 5 different user mentions as parameters.
   - ~!reveal~ to reveal everyone's location.
   - ~!timer <seconds>~ to start a timer. This command accepts one parameter as the length in seconds for the timer.
*** Commands used in a DM chat with bot
   - ~!goto <place>~ to set your next location. This command accepts 1 parameter from the following values: ~airport~, ~bar~, ~casino~, ~hotel~, ~villa~.
   - ~!barrier <place>~ to set a barrier at a location. This command accepts 1 parameter from the following values: ~airport~, ~bar~, ~casino~, ~hotel~, ~villa~